var d=null,l=null,m=null,p=null,q=null,t=null,u=null,w="normal",x=["normal","sleeping","density"];function aa(){for(var a,b=t,c=y*z-1;0<=c;c--)a=c*A,"sleeping"===w||"normal"===w?(b[4*c+0]=B[a+C.r],b[4*c+1]=B[a+C.g],b[4*c+2]=B[a+C.b],b[4*c+3]=255,"sleeping"===w&&1===B[a+C.sleeping]&&(b[4*c]=0,b[4*c+1]=0,b[4*c+2]=0)):"density"===w&&(b[4*c+0]=~~(255*.01*B[a+C.density]),b[4*c+1]=0,b[4*c+2]=255-~~(255*.01*B[a+C.density]),b[4*c+3]=255);m.putImageData(q,0,0);p.drawImage(l,0,0,1*l.width,1*l.height)};window.addEventListener("load",function(){ba(function(a){D=a;ea()})},!1);var D=null;
function ea(){fa();ga();d=document.getElementById("display");d.width=1*y;d.height=1*z;l=document.createElement("canvas");l.width=y;l.height=z;p=d.getContext("2d",{alpha:!1});m=l.getContext("2d",{alpha:!1});q=m.getImageData(0,0,y,z);t=q.data;u=document.getElementById("container");u.style.marginLeft=~~(.5*-u.offsetWidth)+"px";u.style.marginTop=~~(.5*-u.offsetHeight)+"px";for(var a=document.createElement("select"),b=0;b<E.length;b++){var c=document.createElement("option");c.value=E[b];c.innerHTML=E[b];
a.appendChild(c)}a.addEventListener("change",function(){F=E[a.selectedIndex]},!1);a.selectedIndex=J[F];u.appendChild(a);b=document.createElement("button");b.innerHTML="clear all";b.addEventListener("click",K,!1);u.appendChild(b);for(var k=document.createElement("select"),b=0;b<x.length;b++)c=document.createElement("option"),c.value=x[b],c.innerHTML=x[b],k.appendChild(c);k.addEventListener("change",function(){w=x[k.selectedIndex]},!1);k.selectedIndex=x[0];u.appendChild(k);setInterval(ha,1E3/60);d.addEventListener("mousedown",
function(a){a.preventDefault();L=!0},!1);u.addEventListener("mousemove",function(a){a.preventDefault();var b=d.offsetTop+u.offsetTop;M=~~((a.pageX-(d.offsetLeft+u.offsetLeft))/1);N=~~((a.pageY-b)/1)},!1);document.addEventListener("mouseup",function(){L=!1},!1)}var M=0,N=0,O=0,P=0,L=!1;function ba(a){var b=new XMLHttpRequest;b.onload=function(){if(200===b.status&&b.responseText){var c=JSON.parse(b.responseText);a(c)}};b.open("GET","particles.json?"+Date.now(),!0);try{b.send()}catch(c){a(!1)}}
function ia(a){var b=O,c=P,k=M+1,g=N+1,f;f=4;var e,h,k=b-k;e=c-g;g=Math.abs(k)>Math.abs(e)?Math.abs(k):Math.abs(e);k/=g/f;e/=g/f;h=c;for(c=1;c<=g;c+=f)a(Math.floor(b),Math.floor(h)),b-=k,h-=e}function Q(a,b,c){0>c?c+=1:1<c&&--c;return 1>6*c?a+6*(b-a)*c:1>2*c?b:2>3*c?a+(b-a)*(2/3-c)*6:a}function ja(a,b,c){var k=0,g=0,f=0;a=a/360;if(0==b)k=g=f=255*c;else var e=f=0,e=.5>c?c*(1+b):c+b-b*c,f=2*c-e,k=255*Q(f,e,a+1/3),g=255*Q(f,e,a),f=255*Q(f,e,a-1/3);return[Math.round(k),Math.round(g),Math.round(f)]}
var R=[],S=0;function fa(){for(var a=0;2048>a;a++)R.push(Math.random())}function T(){++S>=R.length&&(S=0);return R[S]};var y=600,z=400,U=0,B=null,V=null,J={},E=null,F="sand",C={type:0,moved:1,sleeping:2,vel:3},A=0;function ga(){A=D.properties.length+4;B=new Uint8Array(y*z*A);V=new Uint8Array(A);var a=0,b;for(b in D.types)D.types.hasOwnProperty(b)&&(J.hasOwnProperty(b)||(J[b]=a++));E=Object.keys(J);for(a=0;a<D.properties.length;a++)C[D.properties[a]]=a+4;Object.keys(C);K()}
function ha(){U++;if(L){var a=3*U%360,b=.7,c=.4;switch(F){case "sand":b=.7;c=.4;break;case "silt":b=.1,c=.6}var a=ja(a,b,c),k={r:a[0],g:a[1],b:a[2]};ia(function(a,b){ka(a-8,b-8,16,16,F,"sand"===F||"silt"===F?k:void 0)})}O=M;P=N;for(a=y*z-1;0<=a;a--)B[a*A+C.moved]=0;b=0;for(c=z-1;0<=c;c--){for(var g=0;g<y;g++){var f=Math.abs(b-g),a=W(f,c);if(0<B[a+C.life]&&0>=--B[a+C.life])X(f,c,"air");else if(0===B[a+C.moved]&&1===B[a+C.physics]&&1!==B[a+C.sleeping]){var e=f,h=c,v=B[a+C.vel];la(a,v=Math.min(ma(B[a+
C.vmax]),v+1));for(var G=Math.abs(B[a+C.vel]);0<=G;G--){a=W(e,h);if(B[a]===J.fire)if(1!==B[a+C.density]){X(e,h,"fire");break}else{var r=W(f,c-1),n=W(f-1,c),ca=W(f+1,c),da=W(f,c+1),H=C.flammable,I=J.fire;1===B[r+H]&&(B[r]=I);1===B[n+H]&&(B[n]=I);1===B[ca+H]&&(B[ca]=I);1===B[da+H]&&(B[da]=I)}n=1;r=0>v?-1:1;Y(e,h,e,h+r)&&(n=.05,h+=r);T()<.5*n?(n=.5>T()?-1:1,Y(e,h,e-n,h+r)?(e-=n,h+=r):Y(e,h,e+n,h+r)?(e+=n,h+=r):1===B[a+C.liquid]&&(Y(e,h,e-n,h)?(e-=n,Y(e,h,e-n,h)&&(e-=n)):Y(e,h,e+n,h)&&(e+=n,Y(e,h,e+n,
h)&&(e+=n)))):(la(a,0),1===B[a+C.solid]&&(B[a+C.sleeping]=0));0===B[a+C.solid]&&(B[a+C.sleeping]=1)}}}b=y-1-b}aa()}function W(a,b){a=Math.max(0,Math.min(y-1,a));b=Math.max(0,Math.min(z-1,b));return(b*y+a)*A}function la(a,b){B[a+C.vel]=b}function K(){ka(0,0,y,z,"air")}function ka(a,b,c,k,g,f){X(a,b,g,f);f=W(a,b);var e=A-1;for(g=e;0<=g;g--)V[g]=B[f+g];for(var h=a;h<a+c;h++)for(var v=b;v<b+k;v++)for(f=W(h,v),g=e;0<=g;g--)B[f+g]=V[g]}
function X(a,b,c,k){if(!(0>a||0>b||a>=y||b>=z)){"object"!==typeof k&&(k={});var g={type:J[c],moved:!1,sleeping:!1,vel:0};c=D.types[c];for(var f in c)k.hasOwnProperty(f)?g[f]=k[f]:c.hasOwnProperty(f)&&(g[f]=c[f]);k=W(a,b);Z(a,b);a=Object.keys(g);for(b=A-1;0<=b;b--)B[k+b]=Number(g["undefined"===typeof a[b]?0:a[b]])}}
function Y(a,b,c,k){var g=W(a,b),f=W(c,k),e=B[g+C.density],h=B[f+C.density];if(1===B[f+C.solid]){if(h>=e)return B[g+C.sleeping]=1,!1;if(T()>=.01*(e-h))return!1}Z(a,b);Z(c,k);B[g+C.moved]=1;for(a=A;a--;)V[a]=B[g+a],B[g+a]=B[f+a],B[f+a]=V[a];return!0}function Z(a,b){var c=C.sleeping,k=W(a-1,b-1),g=W(a,b-1),f=W(a+1,b-1),e=W(a-1,b),h=W(a+1,b),v=W(a-1,b+1),G=W(a,b+1),r=W(a+1,b+1);B[k+c]=0;B[g+c]=0;B[f+c]=0;B[e+c]=0;B[h+c]=0;B[v+c]=0;B[G+c]=0;B[r+c]=0}function ma(a){return 128>a?a:-254+a};
