var d=null,m=null,n=null,q=null,r=null,aa=null,t=null,u="normal",v=["normal","sleeping","density"];function ba(){for(var a,b=aa,c=x*y-1;0<=c;c--)a=c*z,"sleeping"===u||"normal"===u?(b[4*c+0]=A[a+B.r],b[4*c+1]=A[a+B.g],b[4*c+2]=A[a+B.b],b[4*c+3]=255,"sleeping"===u&&A[a+B.sleeping]&&(b[4*c]=0,b[4*c+1]=0,b[4*c+2]=0)):"density"===u&&(b[4*c+0]=~~(255*.01*A[a+ca.a.density]),b[4*c+1]=0,b[4*c+2]=255-~~(255*.01*A[a+ca.a.density]),b[4*c+3]=255);n.putImageData(r,0,0);q.drawImage(m,0,0,2*m.width,2*m.height)};window.addEventListener("load",function(){da(function(a){C=a;ea()})},!1);var C=null;
function ea(){fa();ga();d=document.getElementById("display");d.width=2*x;d.height=2*y;m=document.createElement("canvas");m.width=x;m.height=y;q=d.getContext("2d",{alpha:!1});n=m.getContext("2d",{alpha:!1});r=n.getImageData(0,0,x,y);aa=r.data;q.imageSmoothingEnabled=!1;q.mozImageSmoothingEnabled=!1;q.webkitImageSmoothingEnabled=!1;t=document.getElementById("container");t.style.marginLeft=~~(.5*-t.offsetWidth)+"px";t.style.marginTop=~~(.5*-t.offsetHeight)+"px";for(var a=document.createElement("select"),
b=0;b<D.length;b++){var c=document.createElement("option");c.value=D[b];c.innerHTML=D[b];a.appendChild(c)}a.addEventListener("change",function(){E=D[a.selectedIndex]},!1);a.selectedIndex=F[E];t.appendChild(a);b=document.createElement("button");b.innerHTML="clear all";b.addEventListener("click",ha,!1);t.appendChild(b);for(var h=document.createElement("select"),b=0;b<v.length;b++)c=document.createElement("option"),c.value=v[b],c.innerHTML=v[b],h.appendChild(c);h.addEventListener("change",function(){u=
v[h.selectedIndex]},!1);h.selectedIndex=v[0];t.appendChild(h);requestAnimationFrame(ia);d.addEventListener("mousedown",function(a){a.preventDefault();G=!0},!1);t.addEventListener("mousemove",function(a){a.preventDefault();var b=d.offsetTop+t.offsetTop;H=~~((a.pageX-(d.offsetLeft+t.offsetLeft))/2);I=~~((a.pageY-b)/2)},!1);document.addEventListener("mouseup",function(){G=!1},!1)}var H=0,I=0,ja=0,ka=0,G=!1;
function da(a){var b=new XMLHttpRequest;b.onload=function(){if(200===b.status&&b.responseText){var c=JSON.parse(b.responseText);a(c)}};b.open("GET","particles.json?"+Date.now(),!0);try{b.send()}catch(c){a(!1)}}function na(a){var b=ja,c=ka,h=H+1,g=I+1,f;f=2;var l,e,h=b-h;l=c-g;g=Math.abs(h)>Math.abs(l)?Math.abs(h):Math.abs(l);h/=g/f;l/=g/f;e=c;for(c=1;c<=g;c+=f)a(Math.floor(b),Math.floor(e)),b-=h,e-=l}function J(a,b,c){0>c?c+=1:1<c&&--c;return 1>6*c?a+6*(b-a)*c:1>2*c?b:2>3*c?a+(b-a)*(2/3-c)*6:a}
function oa(a,b,c){var h=0,g=0,f=0;a=a/360;if(0==b)h=g=f=255*c;else var l=f=0,l=.5>c?c*(1+b):c+b-b*c,f=2*c-l,h=255*J(f,l,a+1/3),g=255*J(f,l,a),f=255*J(f,l,a-1/3);return[Math.round(h),Math.round(g),Math.round(f)]}var O=[],P=0;function fa(){for(var a=0;2048>a;a++)O.push(Math.random())}function Q(){++P>=O.length&&(P=0);return O[P]};var x=500,y=300,pa=0,A=null,R=null,S=null,F={},D=null,E="sand",B={type:0,moved:1,sleeping:2,vel:3},T={},U=null,V=0,z=0;
function ga(){V=C.iproperties.length;z=C.eproperties.length+4;A=new Uint8Array(x*y*z);S=new Uint8Array(z);var a=0,b;for(b in C.types)C.types.hasOwnProperty(b)&&(F.hasOwnProperty(b)||(F[b]=a++));D=Object.keys(F);for(a=0;a<C.eproperties.length;a++)B[C.eproperties[a]]=a+4;Object.keys(B);for(a=0;a<C.iproperties.length;a++)T[C.iproperties[a]]=a;U=Object.keys(T);R=new Uint8Array(V*D.length);for(a=0;a<D.length-1;a++){b=0;for(var c=U.length;b<c;b++)R[a*c+b]=C.types[D[a]][U[b]]}ha()}
function ia(){pa++;if(G){var a=3*pa%360,b=.7,c=.4;switch(E){case "sand":b=.7;c=.4;break;case "silt":b=.1,c=.6}var a=oa(a,b,c),h={r:a[0],g:a[1],b:a[2]};na(function(a,b){qa(a-4,b-4,8,8,E,"sand"===E||"silt"===E?h:void 0)})}ja=H;ka=I;for(a=x*y-1;0<=a;a--)A[a*z+B.moved]=0;b=0;for(c=y-1;0<=c;c--){for(var g=0;g<x;g++){var f=Math.abs(b-g),a=W(f,c),l=A[a+B.type];if(!(0<A[a+B.life]&&0>=--A[a+B.life]||0!==A[a+B.moved]||1!==R[l*V+T.physics]||A[a+B.sleeping])){var e=f,k=c,K=A[a+B.vel];ra(a,K=Math.min(sa(R[l*V+
T.vmax]),K+1));for(var L=Math.abs(A[a+B.vel]);0<=L;L--){a=W(e,k);if(A[a]===F.fire)if(1!==X(l)){ta(e,k,"fire");break}else{var w=W(f,c-1),p=W(f-1,c),la=W(f+1,c),ma=W(f,c+1),M=B.flammable,N=F.fire;1===A[w+M]&&(A[w]=N);1===A[p+M]&&(A[p]=N);1===A[la+M]&&(A[la]=N);1===A[ma+M]&&(A[ma]=N)}p=1;w=0>K?-1:1;Y(e,k,e,k+w)&&(p=.05,k+=w);Q()<.5*p?(p=.5>Q()?-1:1,Y(e,k,e-p,k+w)?(e-=p,k+=w):Y(e,k,e+p,k+w)?(e+=p,k+=w):1===R[l*V+T.liquid]&&(Y(e,k,e-p,k)?(e-=p,Y(e,k,e-p,k)&&(e-=p)):Y(e,k,e+p,k)&&(e+=p,Y(e,k,e+p,k)&&(e+=
p)))):(ra(a,0),Z(l)&&(A[a+B.sleeping]=0));Z(l)||(A[a+B.sleeping]=1)}}}b=x-1-b}ba();requestAnimationFrame(ia)}function W(a,b){a=Math.max(0,Math.min(x-1,a));b=Math.max(0,Math.min(y-1,b));return(b*x+a)*z}function X(a){return R[a*V+T.density]}function Z(a){return 1===R[a*V+T.solid]}function ra(a,b){A[a+B.vel]=b}function ha(){qa(0,0,x,y,"air")}
function qa(a,b,c,h,g,f){ta(a,b,g,f);f=W(a,b);var l=z-1;for(g=l;0<=g;g--)S[g]=A[f+g];for(var e=a;e<a+c;e++)for(var k=b;k<b+h;k++)for(f=W(e,k),g=l;0<=g;g--)A[f+g]=S[g]}
function ta(a,b,c,h){if(!(0>a||0>b||a>=x||b>=y)){"object"!==typeof h&&(h={});var g={type:F[c],moved:!1,sleeping:!1,vel:0};c=C.types[c];for(var f in c)h.hasOwnProperty(f)?g[f]=h[f]:c.hasOwnProperty(f)&&B.hasOwnProperty(f)&&(g[f]=c[f]);h=W(a,b);ua(a,b);a=Object.keys(g);for(b=z-1;0<=b;b--)A[h+b]=Number(g["undefined"===typeof a[b]?0:a[b]])}}
function Y(a,b,c,h){var g=W(a,b),f=W(c,h),l=A[f+B.type],e=X(A[g+B.type]),k=X(l);if(Z(l)){if(k>=e)return A[g+B.sleeping]=1,!1;if(Q()>=.01*(e-k))return!1}ua(a,b);ua(c,h);A[g+B.moved]=1;for(a=z;a--;)S[a]=A[g+a],A[g+a]=A[f+a],A[f+a]=S[a];return!0}function ua(a,b){var c=B.sleeping,h=W(a-1,b-1),g=W(a,b-1),f=W(a+1,b-1),l=W(a-1,b),e=W(a+1,b),k=W(a-1,b+1),K=W(a,b+1),L=W(a+1,b+1);A[h+c]=0;A[g+c]=0;A[f+c]=0;A[l+c]=0;A[e+c]=0;A[k+c]=0;A[K+c]=0;A[L+c]=0}var ca={};function sa(a){return 128>a?a:-254+a};
