var d=null,m=null,n=null,q=null,r=null,aa=null,t=null,u="normal",v=["normal","sleeping","density"];function ba(){for(var a,b=aa,c=w*x-1;0<=c;c--)a=c*y,"sleeping"===u||"normal"===u?(b[4*c+0]=A[a+B.r],b[4*c+1]=A[a+B.g],b[4*c+2]=A[a+B.b],b[4*c+3]=255,"sleeping"===u&&A[a+B.sleeping]&&(b[4*c]=0,b[4*c+1]=0,b[4*c+2]=0)):"density"===u&&(a=C(A[a]),b[4*c+0]=~~(255*.01*a),b[4*c+1]=0,b[4*c+2]=255-~~(255*.01*a),b[4*c+3]=255);n.putImageData(r,0,0);q.globalAlpha=.5;q.drawImage(m,0,0,2*m.width,2*m.height)};window.addEventListener("load",function(){ca(function(a){D=a;da()})},!1);var D=null;
function da(){ea();fa();d=document.getElementById("display");d.width=2*w;d.height=2*x;m=document.createElement("canvas");m.width=w;m.height=x;q=d.getContext("2d",{alpha:!1});n=m.getContext("2d",{alpha:!1});r=n.getImageData(0,0,w,x);aa=r.data;q.imageSmoothingEnabled=!1;q.mozImageSmoothingEnabled=!1;q.webkitImageSmoothingEnabled=!1;t=document.getElementById("container");t.style.marginLeft=~~(.5*-t.offsetWidth)+"px";t.style.marginTop=~~(.5*-t.offsetHeight)+"px";for(var a=document.createElement("select"),
b=0;b<E.length;b++){var c=document.createElement("option");c.value=E[b];c.innerHTML=E[b];a.appendChild(c)}a.addEventListener("change",function(){F=E[a.selectedIndex]},!1);a.selectedIndex=G[F];t.appendChild(a);b=document.createElement("button");b.innerHTML="clear all";b.addEventListener("click",ga,!1);t.appendChild(b);for(var h=document.createElement("select"),b=0;b<v.length;b++)c=document.createElement("option"),c.value=v[b],c.innerHTML=v[b],h.appendChild(c);h.addEventListener("change",function(){u=
v[h.selectedIndex]},!1);h.selectedIndex=v[0];t.appendChild(h);requestAnimationFrame(ha);d.addEventListener("mousedown",function(a){a.preventDefault();H=!0},!1);t.addEventListener("mousemove",function(a){a.preventDefault();var b=d.offsetTop+t.offsetTop;I=~~((a.pageX-(d.offsetLeft+t.offsetLeft))/2);J=~~((a.pageY-b)/2)},!1);document.addEventListener("mouseup",function(){H=!1},!1)}var I=0,J=0,ia=0,ja=0,H=!1;
function ca(a){var b=new XMLHttpRequest;b.onload=function(){if(200===b.status&&b.responseText){var c=JSON.parse(b.responseText);a(c)}};b.open("GET","particles.json?"+Date.now(),!0);try{b.send()}catch(c){a(!1)}}function na(a){var b=ia,c=ja,h=I+1,g=J+1,f;f=2;var l,e,h=b-h;l=c-g;g=Math.abs(h)>Math.abs(l)?Math.abs(h):Math.abs(l);h/=g/f;l/=g/f;e=c;for(c=1;c<=g;c+=f)a(Math.floor(b),Math.floor(e)),b-=h,e-=l}function L(a,b,c){0>c?c+=1:1<c&&--c;return 1>6*c?a+6*(b-a)*c:1>2*c?b:2>3*c?a+(b-a)*(2/3-c)*6:a}
function oa(a,b,c){var h=0,g=0,f=0;a=a/360;if(0==b)h=g=f=255*c;else var l=f=0,l=.5>c?c*(1+b):c+b-b*c,f=2*c-l,h=255*L(f,l,a+1/3),g=255*L(f,l,a),f=255*L(f,l,a-1/3);return[Math.round(h),Math.round(g),Math.round(f)]}var O=[],P=0;function ea(){for(var a=0;2048>a;a++)O.push(Math.random())}function Q(){++P>=O.length&&(P=0);return O[P]};var w=400,x=300,pa=0,A=null,R=null,S=null,G={},E=null,F="sand",B={type:0,moved:1,sleeping:2,vel:3},T={},U=null,V=0,y=0;
function fa(){V=D.iproperties.length;y=D.eproperties.length+4;A=new Uint8Array(w*x*y);S=new Uint8Array(y);var a=0,b;for(b in D.types)D.types.hasOwnProperty(b)&&(G.hasOwnProperty(b)||(G[b]=a++));E=Object.keys(G);for(a=0;a<D.eproperties.length;a++)B[D.eproperties[a]]=a+4;Object.keys(B);for(a=0;a<D.iproperties.length;a++)T[D.iproperties[a]]=a;U=Object.keys(T);R=new Uint8Array(V*E.length);for(a=0;a<E.length-1;a++){b=0;for(var c=U.length;b<c;b++)R[a*c+b]=D.types[E[a]][U[b]]}ga()}
function ha(){pa++;if(H){var a=3*pa%360,b=.7,c=.4;switch(F){case "sand":b=.7;c=.4;break;case "silt":b=.1,c=.6}var a=oa(a,b,c),h={r:a[0],g:a[1],b:a[2]};na(function(a,b){qa(a-3,b-3,6,6,F,"sand"===F||"silt"===F?h:void 0)})}ia=I;ja=J;for(a=w*x-1;0<=a;a--)A[a*y+B.moved]=0;b=0;for(c=x-1;0<=c;c--){for(var g=0;g<w;g++){var f=Math.abs(b-g),a=W(f,c),l=A[a+B.type];if(0<A[a+B.life]&&0>=--A[a+B.life])X(f,c,"air");else if(0===ra(!1,"moved",a)&&1===R[l*V+T.physics]&&!A[a+B.sleeping]){var e=f,k=c,K=A[a+B.vel];sa(a,
K=Math.min(ta(R[l*V+T.vmax]),K+1));for(var ka=Math.abs(A[a+B.vel]);0<=ka;ka--){a=W(e,k);if(A[a]===G.fire)if(1!==C(l)){X(e,k,"fire");break}else{var z=W(f,c-1),p=W(f-1,c),la=W(f+1,c),ma=W(f,c+1),M=B.flammable,N=G.fire;1===A[z+M]&&(A[z]=N);1===A[p+M]&&(A[p]=N);1===A[la+M]&&(A[la]=N);1===A[ma+M]&&(A[ma]=N)}p=1;z=0>K?-1:1;Y(e,k,e,k+z)&&(p=ra(!0,"turbulence",l)/200,k+=z);Q()<.5*p?(p=.5>Q()?-1:1,Y(e,k,e-p,k+z)?(e-=p,k+=z):Y(e,k,e+p,k+z)?(e+=p,k+=z):1===R[l*V+T.liquid]&&(Y(e,k,e-p,k)?(e-=p,Y(e,k,e-p,k)&&
(e-=p)):Y(e,k,e+p,k)&&(e+=p,Y(e,k,e+p,k)&&(e+=p)))):(sa(a,0),Z(l)&&(A[a+B.sleeping]=0));Z(l)||(A[a+B.sleeping]=1)}}}b=w-1-b}ba();requestAnimationFrame(ha)}function W(a,b){a=Math.max(0,Math.min(w-1,a));b=Math.max(0,Math.min(x-1,b));return(b*w+a)*y}function ra(a,b,c){return a?R[c*V+T[b]]:A[c+B[b]]}function C(a){return R[a*V+T.density]}function Z(a){return 1===R[a*V+T.solid]}function sa(a,b){A[a+B.vel]=b}function ga(){qa(0,0,w,x,"air")}
function qa(a,b,c,h,g,f){X(a,b,g,f);f=W(a,b);var l=y-1;for(g=l;0<=g;g--)S[g]=A[f+g];for(var e=a;e<a+c;e++)for(var k=b;k<b+h;k++)for(f=W(e,k),g=l;0<=g;g--)A[f+g]=S[g]}
function X(a,b,c,h){if(!(0>a||0>b||a>=w||b>=x)){"object"!==typeof h&&(h={});var g={type:G[c],moved:!1,sleeping:!1,vel:0};c=D.types[c];for(var f in c)h.hasOwnProperty(f)?g[f]=h[f]:c.hasOwnProperty(f)&&B.hasOwnProperty(f)&&(g[f]=c[f]);h=W(a,b);ua(a,b);a=Object.keys(g);for(b=y-1;0<=b;b--)A[h+b]=Number(g["undefined"===typeof a[b]?0:a[b]])}}
function Y(a,b,c,h){var g=W(a,b),f=W(c,h),l=A[f+B.type],e=C(A[g+B.type]),k=C(l);if(Z(l)){if(1!==R[l*V+T.liquid]||k>=e)return A[g+B.sleeping]=1,!1;if(Q()>=.01*(e-k))return!1}ua(a,b);ua(c,h);A[g+B.moved]=1;for(a=y;a--;)S[a]=A[g+a],A[g+a]=A[f+a],A[f+a]=S[a];return!0}function ua(a,b){var c=B.sleeping,h=W(a,b-1),g=W(a+1,b-1),f=W(a-1,b),l=W(a+1,b),e=W(a-1,b+1),k=W(a,b+1),K=W(a+1,b+1);A[W(a-1,b-1)+c]=0;A[h+c]=0;A[g+c]=0;A[f+c]=0;A[l+c]=0;A[e+c]=0;A[k+c]=0;A[K+c]=0}function ta(a){return 128>a?a:-254+a};
